### ISSUE TITLE
Coins/Shop

### ISSUE THREAD

**Issue by E3Twixy** [eelwelll/Project-Plane#1]
Coins add infinitley upon death

Coins dont say when i uhhhh uh um uhhhhhhhhhh like die ands press main menu
alsop like the thingy thwe score doesnt say it rightr on the ytou died thing fix this pls xoxo
love, 
        Kaitlyn

**Comment by eelwelll** [comment]
I fixed in new patch which will release tonight probably or in the coming days :D 
Thank you Kaitlyn.

**Comment by E3Twixy** [comment]
No problem pookie xoxoxoxo
lots of love, 
Kavanaugh
